const ROLE_STORY_SCHEMA_VERSION = 2
const BOOK_TEXT_SCHEMA_VERSION = 3
const PLOT_TEXT_SCHEMA_VERSION = 3
const MAP_TEXT_SCHEMA_VERSION = 3
const BACKPACK_TEXT_SCHEMA_VERSION = 3

const INTERACTIVE_DIALOGUE_PIPELINE_VERSION = 2

const INTERACTIVE_PARSE_PIPELINE_KEYS = {
  plot: 'plotInteractiveParse',
  map: 'mapInteractiveParse',
  anecdote: 'anecdoteInteractiveParse'
}

export {
  ROLE_STORY_SCHEMA_VERSION,
  BOOK_TEXT_SCHEMA_VERSION,
  PLOT_TEXT_SCHEMA_VERSION,
  MAP_TEXT_SCHEMA_VERSION,
  BACKPACK_TEXT_SCHEMA_VERSION,
  INTERACTIVE_DIALOGUE_PIPELINE_VERSION,
  INTERACTIVE_PARSE_PIPELINE_KEYS
}
